version: '3'
services:
  app:
    restart: unless-stopped
    image: irithm
    build:
      context: ./
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://irithm:irithm@postgres:5432/irithm
      - TEST_DATABASE_URL=postgresql://irithm_test:irithm_test@postgres:5432/irithm_test
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - '.:/irithm'
  postgres:
    restart: unless-stopped
    image: postgres:10.4
    environment:
      POSTGRES_DB: irithm
      POSTGRES_USER: irithm
      POSTGRES_PASSWORD: irithm
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'
      - 'postgres-data:/var/lib/postgresql/data'
  test_postgres:
    restart: unless-stopped
    image: postgres:10.4-alpine
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: irithm_test
      POSTGRES_USER: irithm_test
      POSTGRES_PASSWORD: irithm_test
volumes:
  postgres-data: