from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca2317ac876'
down_revision = 'e73c51aec297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('card', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('list', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('list', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('list', 'updated_at')
    op.drop_column('list', 'created_at')
    op.drop_column('comment', 'updated_at')
    op.drop_column('comment', 'created_at')
    op.drop_column('card', 'updated_at')
    op.drop_column('card', 'created_at')
    # ### end Alembic commands ###
